Improvements and fixes
koishijs/koishi-plugin-adapter-minecraft pull request #2
Opened 2022-01-13 13:53 UTC by DDEle

More options with schema:
* common mineflayer options
* rate limit
* server message and its "author"

Events:
* `minecraft/before-listen`: fired after logged in but before start listening messages (for some in-game initialization behavior).
* `minecraft/before-message`: fired before dispatch message sessions.

2022-01-13 17:11 UTC, Shigma requested changes

2022-01-13 17:11 UTC, Shigma commented on src/bot.ts
> +      Schema.const('microsoft' as 'microsoft'),
小技巧：as const

2022-01-13 17:11 UTC, Shigma commented on src/index.ts
> +  interface EventMap {
前面加个空行吧

2022-01-13 17:11 UTC, Shigma commented on src/bot.ts
> +    receiveMessage: Schema.union([
总感觉这个配置项名字有点怪……

receiveMessage 是一个动词短语，为啥类型是一个对象呢？改成 author 之类的名称短语是不是会好一点？

2022-01-14 07:55 UTC, Shigma commented on src/bot.ts
> +    content = segment.join(segment.parse(content).map(i => i.type !== 'text'
是不是可以用 segment.transform

2022-01-14 07:55 UTC, Shigma commented on src/index.ts
> +    'minecraft/before-message'(session?: Session): Session | undefined
这里是不是不应该问号

2022-01-14 10:55 UTC, DDEle commented on src/index.ts
> +    'minecraft/before-message'(session?: Session): Session | undefined
后面调用的时候用的waterfall（要不就是chain），不是说输入是上一个的输出么？

2022-01-14 11:01 UTC, DDEle commented on src/bot.ts
> +    content = segment.join(segment.parse(content).map(i => i.type !== 'text'
才知道，文档没有这方法（

2022-01-14 11:25 UTC, Shigma commented on src/index.ts
> +    'minecraft/before-message'(session?: Session): Session | undefined
之前没仔细看代码抱歉。

1. 你这个根本不适合 chain，就应该 emit
2. 也不应该叫 before-message，可以叫 dispatch 之类的名字
3. 建议直接 override 父类方法而不是用箭头函数赋值

2022-01-14 19:18 UTC, DDEle commented
@Shigma 麻烦 `index` 里加一下 `export * from './bot'` 和 `export * from './ws'`

2022-03-04 21:07 UTC, merged